# Exploratory Data Analysis (EDA)

## Loading Dataset, Descriptive Statistics, Missing Values and Duplicates

This notebook demonstrates the basic steps of Exploratory Data Analysis using Pandas.

In [1]:
import pandas as pd

In [2]:
# Creating a sample student dataset

data = {
    "Name": ["Akash", "Rahul", "Priya", "Sneha", "Arjun", "Rahul", "Meena"],
    "Age": [20, 21, 20, None, 22, 21, 20],
    "Marks": [85, 78, 92, 88, None, 78, 95],
    "Department": ["CSE", "ISE", "CSE", "ECE", "CSE", "ISE", "ECE"]
}

df = pd.DataFrame(data)

df

    Name   Age  Marks Department
0  Akash  20.0   85.0        CSE
1  Rahul  21.0   78.0        ISE
2  Priya  20.0   92.0        CSE
3  Sneha   NaN   88.0        ECE
4  Arjun  22.0    NaN        CSE
5  Rahul  21.0   78.0        ISE
6  Meena  20.0   95.0        ECE

In [3]:
# Display first five rows

print("First five rows:")
display(df.head())

First five rows:

    Name   Age  Marks Department
0  Akash  20.0   85.0        CSE
1  Rahul  21.0   78.0        ISE
2  Priya  20.0   92.0        CSE
3  Sneha   NaN   88.0        ECE
4  Arjun  22.0    NaN        CSE

In [4]:
# Descriptive statistics for numerical columns

print("Descriptive Statistics:")
display(df.describe())

Descriptive Statistics:

             Age      Marks
count   6.000000   6.000000
mean   20.666667  86.000000
std     0.816497   7.071068
min    20.000000  78.000000
25%    20.000000  79.750000
50%    20.500000  86.500000
75%    21.000000  91.000000
max    22.000000  95.000000

In [5]:
# Checking missing values in each column

print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Name          0
Age           1
Marks         1
Department    0
dtype: int64

In [6]:
# Total missing values

total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 2

In [7]:
# Display rows containing at least one missing value

missing_rows = df[df.isnull().any(axis=1)]

print("Rows containing missing values:")
display(missing_rows)

Rows containing missing values:

    Name   Age  Marks Department
3  Sneha   NaN   88.0        ECE
4  Arjun  22.0    NaN        CSE

In [8]:
# Checking for duplicate rows

duplicates = df.duplicated()

print("Duplicate rows:")
display(df[duplicates])

Duplicate rows:

    Name   Age  Marks Department
5  Rahul  21.0   78.0        ISE

In [9]:
# Count the number of duplicate rows

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 1

NameError: name 'df_cleaned' is not defined